### ISSUE TITLE
What's the license?

### ISSUE THREAD

**Issue by therealjoesmith** [prebid/headerbid-expert#13]
Hi

What is the license of the files in this repo? I want to use it for my school project if allowed by license.

Thanks
Joe

**Comment by mkendall07** [comment]
Should be apache 2 (https://github.com/prebid/Prebid.js/blob/master/LICENSE). Looks like we forgot to add it this repo. Thanks for pointing it out!

**Comment by therealjoesmith** [comment]
Thank you!
